Iteration 5
109th/go-url-shortener pull request #5
Opened 2024-05-05 10:58 UTC by 109th

2024-05-07 07:19 UTC, s-shpak requested changes
Добавь `golangci-lint` в Github Actions, как описано здесь: https://github.com/s-shpak/praktikum-golangci-lint?tab=readme-ov-file#настройка-github-actions

2024-05-07 07:19 UTC, s-shpak commented on cmd/shortener/main.go
> +		panic(err)
Не надо паниковать

2024-05-07 07:19 UTC, s-shpak commented on internal/app/handlers/config/config.go
> +		panic(err)
Не надо паниковать из глубины кода. См. видео: https://app.pachca.com/chats/9180496?message=234290731

2024-05-07 07:19 UTC, s-shpak commented on internal/app/handlers/config/config.go
> +	if envSrvAddr := os.Getenv("SERVER_ADDRESS"); envSrvAddr != "" {
Лучше использовать https://pkg.go.dev/os#LookupEnv

2024-05-07 07:19 UTC, s-shpak commented on internal/app/storage/storage.go
> +type IStorage interface {
Интерфейсы в Go определяются там, где они используются. См. первый вебинар

2024-05-07 07:19 UTC, s-shpak commented on internal/app/storage/types/map.go
> +func NewMapStorage(size int) *MapStorage {
Зачем `size`? Они ни на что не повлияет

2024-05-07 07:19 UTC, s-shpak commented on internal/app/storage/types/map.go
> +	s.storage[key] = value
Что если такое значение `key` уже есть в хранилище?

2024-05-07 07:19 UTC, s-shpak commented on internal/app/storage/mock/mock.go
> +func NewMockStorage(values map[string]string) *Storage {
Какой смысл в этом моке ? Он просто повторяет реализацию `in-memory` хранилища

2024-05-07 07:19 UTC, s-shpak commented on internal/app/handlers/post.go
> +		res.Write([]byte(config.ServerURLPrefix + "/" + uid))
Используй лучше https://pkg.go.dev/net/url#JoinPath

2024-05-07 07:19 UTC, s-shpak commented on internal/app/handlers/post.go
> +		res.Write([]byte(config.ServerURLPrefix + "/" + uid))
Используй лучше https://pkg.go.dev/net/url#JoinPath

2024-05-12 11:38 UTC, 109th commented on internal/app/storage/mock/mock.go
> +func NewMockStorage(values map[string]string) *Storage {
Смысл был в том чтобы отвязаться от "боевой" реализации хранилища в тестах. В идеале бы замокать все внешние зависимости(storage, server, etc) для юнит тестов, но пока сложно погрузится во все и сразу...

2024-05-12 11:38 UTC, 109th commented
Все замечания исправл

2024-05-13 21:38 UTC, s-shpak requested changes
Выдай мне права контрибьютера в проект, чтобы я мог резолвить комментарии

2024-05-13 21:38 UTC, s-shpak commented on cmd/shortener/main.go
> +		log.Fatalln(fmt.Errorf("flags parse error: %w", err))
```suggestion
		log.Fatalf("flags parse error: %v", err)
```

2024-05-13 21:38 UTC, s-shpak commented on internal/app/config/config.go
> +	if envSrvAddr, found := os.LookupEnv("SERVER_ADDRESS"); found {
В го принято так:

```suggestion
	if envSrvAddr, ok := os.LookupEnv("SERVER_ADDRESS"); ok {
```

2024-05-13 21:38 UTC, s-shpak commented on internal/app/config/config.go
> +var (
Глобальные переменные не нужны, возвращай структуру с этими полями и прокидывай туда, где она нужна

2024-05-13 21:38 UTC, s-shpak commented on internal/app/config/config.go
> +	DefaultAddr        = "localhost:8080"
эти значения не надо делать экспортируемыми

2024-05-13 21:38 UTC, s-shpak commented on internal/app/handlers/get.go
> +			http.Error(res, "500 internal server error", http.StatusInternalServerError)
`Internal Server Error` надо логировать

2024-05-13 21:38 UTC, s-shpak commented on internal/app/handlers/post.go
> +		result, _ := url.JoinPath(config.ServerURLPrefix, uid)
Ошибки надо проверять

2024-05-14 17:42 UTC, 109th commented
@s-shpak Замечания поправил, инвайт закинул

2024-05-15 09:18 UTC, s-shpak approved these changes

2024-05-15 15:11 UTC, merged